routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', App\Http\Livewire\Home::class)->name('home');
Route::get('/service/{slug}', App\Http\Livewire\Service::class)->name('service');

// Profile
Route::get('/about-us', App\Http\Livewire\AboutUs::class)->name('about-us');
Route::get('/team', App\Http\Livewire\Team::class)->name('team');
Route::get('/portfolio', App\Http\Livewire\Portfolio::class)->name('portfolio');

Route::get('/contact-us', App\Http\Livewire\ContactUs::class)->name('contact-us');
Route::get('/term-condition', App\Http\Livewire\TermCond::class)->name('term-condition');
Route::get('/privacy-policy', App\Http\Livewire\PrivacyPolicy::class)->name('privacy-policy');

Route::group([
    'middleware' => ['auth:sanctum', 'verified'],
    'prefix' => 'admin',
    'as' => 'admin.'
], function() {

    Route::get('/dashboard', App\Http\Livewire\Admin\Dashboard::class)->name('dashboard');
    Route::get('/about-us', App\Http\Livewire\Admin\AboutUs::class)->name('about-us');
    Route::get('/tech-expertises', App\Http\Livewire\Admin\TechExpertise::class)->name('tech-expertises');
    Route::get('/services', App\Http\Livewire\Admin\Services::class)->name('services');
    Route::get('/clients', App\Http\Livewire\Admin\Client::class)->name('clients');
    Route::get('/portfolio', App\Http\Livewire\Admin\Portfolio::class)->name('portfolios');
    Route::get('/teams', App\Http\Livewire\Admin\Team::class)->name('teams');
    Route::get('/contact-us', App\Http\Livewire\Admin\ContactUs::class)->name('contact');

    // Configurations
    Route::group([
        'prefix' => 'configuration',
        'as' => 'configuration.'
    ], function() {
        Route::get('/website', App\Http\Livewire\Admin\Config\Website::class)->name('website');
        Route::get('/meta', App\Http\Livewire\Admin\Config\Meta::class)->name('meta');
        Route::get('/social', App\Http\Livewire\Admin\Config\Social::class)->name('social');
        Route::get('/privacy-policy', App\Http\Livewire\Admin\Config\PrivacyPolicy::class)->name('privacy-policy');
        Route::get('/term-cond', App\Http\Livewire\Admin\Config\TermCond::class)->name('term-cond');
    });

});

resources/views/layouts/partials-admin/footer.blade.php
<footer>
    <div class="footer clearfix mb-0 text-muted">
        <div class="float-start">
            <p>2021 &copy; Mazer</p>
        </div>
    </div>
</footer>

resources/views/layouts/partials-admin/header.blade.php
<header class='mb-3'>
    <nav class="navbar navbar-expand navbar-light ">
        <div class="container-fluid">
            <a href="#" class="burger-btn d-block">
                <i class="bi bi-justify fs-3"></i>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {{-- <li class="nav-item dropdown me-1">
                        <a class="nav-link active dropdown-toggle" href="#" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            <i class='bi bi-envelope bi-sub fs-4 text-gray-600'></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                            <li>
                                <h6 class="dropdown-header">Mail</h6>
                            </li>
                            <li><a class="dropdown-item" href="#">No new mail</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown me-3">
                        <a class="nav-link active dropdown-toggle" href="#" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            <i class='bi bi-bell bi-sub fs-4 text-gray-600'></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                            <li>
                                <h6 class="dropdown-header">Notifications</h6>
                            </li>
                            <li><a class="dropdown-item">No notification available</a></li>
                        </ul>
                    </li> --}}
                </ul>
                <div class="dropdown">
                    <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
                        <div class="user-menu d-flex">
                            <div class="user-name text-end me-3">
                                <h6 class="mb-0 text-gray-600">{{ Auth::user()->name }}</h6>
                                <p class="mb-0 text-sm text-success">Online</p>
                            </div>
                            <div class="user-img d-flex align-items-center">
                                <div class="avatar avatar-md">
                                    <img src="{{ Auth::user()->profile_photo_url }}">
                                </div>
                            </div>
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                        <li>
                            <h6 class="dropdown-header">Hello, {{ strtok(Auth::user()->name, " ") }}!</h6>
                        </li>
                        <li><a class="dropdown-item" href="{{ route('profile.show') }}"><i class="icon-mid bi bi-person me-2"></i> My
                                Profile</a></li>
                        @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                        <li>
                            <a class="dropdown-item" href="#"><i class="icon-mid bi bi-gear me-2"></i>
                            {{ __('API Tokens') }}
                            </a>
                        </li>
                        @endif
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                            <li>
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                    <i class="icon-mid bi bi-box-arrow-left me-2"></i>
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>

resources/views/layouts/partials-admin/scripts.blade.php
@livewireScripts
<script src="{{ mix('js/app.js') }}"></script>
<script src="{{ asset('/vendors/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('/vendors/tinymce/tinymce.min.js') }}"></script>
<script src="{{ asset('/js/bootstrap.bundle.min.js') }}"></script>

<script src="{{ asset('/js/main.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.7/dist/sweetalert2.all.min.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", ev => {
        // Toast Alert notification
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
        })

        // To execute alert via livewire
        window.livewire.on('alert', (content = '', status = 'success') => {
            // Status warning, error, success, info
            Toast.fire({
                icon: status,
                title: content,
            })
        })

        // Confirm
        window.livewire.on('confirm', async (id, type = 'delete', title = 'Are you sure?', icon = 'warning', content = '') => {
            const confirm = await Swal.fire({
                title: title,
                icon: icon,
                confirmButtonText: 'Ok',
                showCancelButton: true,
            })

            // If true
            if (confirm.isConfirmed) {
                window.livewire.emit(type, id)
            }
        })

        // Close modal bootstrap 5
        window.livewire.on('closeModal', (id = 'modal-crud') => {
            const myModal = bootstrap.Modal.getInstance(document.getElementById(id))
            // const modalBackdrop = document.getElementsByClassName('modal-backdrop')[0]
            // modalBackdrop.classList.remove('modal-backdrop')
            myModal.hide()
        })

        // Scroll up
        window.livewire.on('scrollUp', () => {
            window.scrollTo(0, 0)
        })
    })
</script>

{{ $script ?? ''}}

resources/views/layouts/partials-admin/sidebar.blade.php
<x-maz-sidebar :href="route('admin.dashboard')" :logo="asset('images/logo/logo.png')">

    <!-- Add Sidebar Menu Items Here -->

    <x-maz-sidebar-item name="Dashboard" :link="route('admin.dashboard')" icon="bi bi-grid-fill"></x-maz-sidebar-item>
    <x-maz-sidebar-item name="About Us" :link="route('admin.about-us')" icon="bi bi-person-square"></x-maz-sidebar-item>
    <x-maz-sidebar-item name="Tech Expertises" :link="route('admin.tech-expertises')" icon="bi bi bi-code"></x-maz-sidebar-item>
    <x-maz-sidebar-item name="Services" :link="route('admin.services')" icon="bi bi-bag-fill"></x-maz-sidebar-item>
    <x-maz-sidebar-item name="Clients" :link="route('admin.clients')" icon="bi bi-file-earmark-person-fill"></x-maz-sidebar-item>
    <x-maz-sidebar-item name="Portfolios" :link="route('admin.portfolios')" icon="bi bi-file-zip"></x-maz-sidebar-item>
    <x-maz-sidebar-item name="Teams" :link="route('admin.teams')" icon="bi bi-emoji-sunglasses"></x-maz-sidebar-item>
    <x-maz-sidebar-item name="Contact" :link="route('admin.contact')" icon="bi bi-headset"></x-maz-sidebar-item>

    <x-maz-sidebar-item name="Configuration" icon="bi bi-file-plus-fill">
        <x-maz-sidebar-sub-item name="Webiste" :link="route('admin.configuration.website')"></x-maz-sidebar-sub-item>
        <x-maz-sidebar-sub-item name="Meta Data" :link="route('admin.configuration.meta')"></x-maz-sidebar-sub-item>
        <x-maz-sidebar-sub-item name="Socials" :link="route('admin.configuration.social')"></x-maz-sidebar-sub-item>
        <x-maz-sidebar-sub-item name="Privacy Policy" :link="route('admin.configuration.privacy-policy')"></x-maz-sidebar-sub-item>
        <x-maz-sidebar-sub-item name="Term & Condition" :link="route('admin.configuration.term-cond')"></x-maz-sidebar-sub-item>
    </x-maz-sidebar-item>

</x-maz-sidebar>

resources/views/layouts/partials-admin/styles.blade.php
<!-- Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

<!-- Vendors -->
<link rel="stylesheet" href="{{ asset('/vendors/perfect-scrollbar/perfect-scrollbar.css') }}">
<link rel="stylesheet" href="{{ asset('/vendors/bootstrap-icons/bootstrap-icons.css') }}">

<!-- Styles -->
<link rel="stylesheet" href="{{ mix('css/bootstrap.css') }}">
<link rel="stylesheet" href="{{ mix('css/app.css') }}">
<link rel="stylesheet" href="{{ mix('css/app-dark.css') }}">

@livewireStyles

{{ $style ?? '' }}